# Generated by Django 4.2.16 on 2026-03-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users_reg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
